using System;

namespace ContractsMvc.Models
{
    /// <summary>
    /// Represents an alert generated by the background service when a
    /// contract or deliverable is approaching its due date or has
    /// passed it. Alerts contain a human readable message and
    /// optionally reference the contract or deliverable that triggered
    /// the alert. Alerts are persisted so that administrators can
    /// review the history of generated notifications.
    /// </summary>
    public class Alert : Entity
    {
        /// <summary>
        /// A descriptive message explaining why the alert was raised.
        /// </summary>
        public string Message { get; set; } = null!;

        /// <summary>
        /// If the alert is associated with a contract this property
        /// contains the identifier of the contract.
        /// </summary>
        public Guid? ContractId { get; set; }
        public Contract? Contract { get; set; }

        /// <summary>
        /// If the alert is associated with a deliverable this property
        /// contains the identifier of the deliverable.
        /// </summary>
        public Guid? DeliverableId { get; set; }
        public Deliverable? Deliverable { get; set; }

        /// <summary>
        /// The date relevant to the alert (e.g. expected delivery date
        /// or contract end date).
        /// </summary>
        public DateTime TargetDate { get; set; }
    }
}